### ISSUE TITLE
Support for change back to AU915 in Australia 

### ISSUE THREAD

**Issue by Psych101** [NebraLtd/helium-nebra-indoor1#1]
This firmware does not support the rollback to AU915 in Australia which was successfully voted and implemented around 17 April 2023. My rockpi hotspot is only sending beacons which are not being witnessed and is not witnessing other beacons. When will the firmware be updated to support this change on the network?

**Comment by shawaj** [comment]
Our hotspots have always supported this frequency plan and still do.

You may need to go into your hotspot local diagnostics and do a factory reset from the "Device Configuration" menu by clicking on "Reset to Factory Defaults"

**Comment by Psych101** [comment]
Hi

Thanks for your email on this. I understand there was recently a vote to
revert back to AU915 following the change to the AS923_1C dual plan. Can
you confirm my hotspot and curret firmware support the change back to AU915?

My hotspot stopped receiving rewards since the change and is only sending
beacons with no witnesses (no issues previously). There are many people in
Australia having similar issues right now.

In the mean time I have done the reset to factory defaults but your advice
on the above would be appreciated.

Regards

Chris

**Comment by shawaj** [comment]
Yes AU915 has always worked on our devices and still does.

You can see the relevant code here... https://github.com/NebraLtd/hm-pktfwd/blob/master/pktfwd/config/lora_templates_sx1301/global_conf.json.AU915_SB2

As long as your device is showing region AU915 on the diagnostics page then everything is working fine.

This region band is pulled automatically from helium gateway-rs software which in turn grabs this from the oracles which base it on the location assert. So it's not something we have direct control over - the region band name is just pulled down directly from there.

**Comment by Psych101** [comment]
Thanks for confirming that. Nothing about my setup has changed. I did a
reset to factory defaults but have since sent a beacon with no witnesses.
Can you think of any reason why I am not being witnessed nor witnessing
since last week? Previously no issues with regular rewards.

Regards

Chris

**Comment by shawaj** [comment]
Might be other hotspots being on the wrong frequency nearby.

If it says au915 on your one, then it's correct

Easiest way to test is with an au915 sensor

**Comment by Psych101** [comment]
Yes it says region plan AU915.  All the hotspots around me are still receiving rewards so it’s a problem with my hotspot it seems.

**Comment by shawaj** [comment]
Check all the antenna connections

**Comment by Psych101** [comment]
Hi 

 

My hotspot just started witnessing after receiving the new firmware v1.0.2-9 a couple of hours ago.  It seems it was a firmware issue after all.  What was the change in the firmware to correct the issue?

 

Regards

 

Chris

**Comment by shawaj** [comment]
@Psych101 the was no change on the packet forwarder or miner

**Comment by Psych101** [comment]
The only other change is that I rebooted but I had already tried that
several times in the past.
