### ISSUE TITLE
How to flash Indoor/Outdoor Gen 1 onboard eMMC NOT WORKING

### ISSUE THREAD

**Issue by USDM2JZ300** [NebraLtd/helium-nebra-indoor1#3]
I follow the instructions exactly how you say to follow them, when running RPIBoot.exe it just continually generates new lines that say "Loading embedded: bootcode.bin" and the light stays on and blue. I then open balena etcher and thats when the light turns off but when i try to flash the file/firmware the compute module drive doesnt show up. This miner has been bricked for like a year and a half. Im tired of trying to fix it with stuff that doesnt work. Even flashing the SD card doesnt work either. Is there a way i can get my money back sending in my miner to you guys that has so many issues?

**Comment by WayneNebra** [comment]
Sorry to hear your having issues, and can you share any ticket numbers for me to look at? also, you can't flash the compute module if it hasn't got onboard eMMC as you mention you've also tried flashing an SD card. 

Please create a ticket and link to your other tickets and I'd be more than happy to look at it for you. 

Please also let me know how your powering it, include some pictures of the miner for me as that would be really useful. 

Thanks 

Wayne

**Comment by USDM2JZ300** [comment]
I am following the guide posted on Friday 12 May 2023 at this link https://support.nebra.com/support/solutions/articles/24000085091-how-to-flash-indoor-outdoor-gen-1-onboard-emmc

I am powering it by plugging the micro usb into the daugther board connection like it says in the guide. 
![IMG_5781](https://github.com/NebraLtd/helium-nebra-indoor1/assets/125909508/fbf9fe7a-a9d7-4851-99f8-18312c0b96d9)
![IMG_5779](https://github.com/NebraLtd/helium-nebra-indoor1/assets/125909508/5195c006-18fc-4777-a1a2-b3742c52783b)

**Comment by USDM2JZ300** [comment]
JP3 is connected, JP4 moved from 1-2 to 2-3, connected micro usb to computer and daughterboard, installed rpiboot, run rpi, and it just keeps saying "Loading embedded: bootcode.bin" and the Blue led does not turn off.
![Capture](https://github.com/NebraLtd/helium-nebra-indoor1/assets/125909508/c2866483-fd4f-4b6c-94be-c87ff71a2904)

**Comment by USDM2JZ300** [comment]
the compute module eMMC does not pop up under Windows as a disk and the Blue LED does not turn off until opening balena etcher but then when i do so it makes the disconnect windows usb sound.

**Comment by USDM2JZ300** [comment]
Ticket (#431107) just created

**Comment by WayneNebra** [comment]
@USDM2JZ300 I'll look at the ticket now. 🙂

**Comment by shawaj** [comment]
You don't need to use rpiboot.exe

Balena Etcher can program compute module directly

**Comment by shawaj** [comment]
Closing as no reply
